-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgeCpE03y4e40YszUV
EpB4ClaNytz8zwcF/6dZtnLbruegCgYIKoZIzj0DAQehRANCAASTSkBC98FXWcwC
cxYseN+fA4sL2reOrfj+guKxCPgRyppKBTdL7hq75YTPqV/5D+MgX2ExhNcVfQAY
rY+lylkA
-----END PRIVATE KEY-----